### ISSUE TITLE
Alive 

### ISSUE THREAD

**Issue by cvsae** [IoTone/TheShellProject#75]
is this project still alive ??

**Comment by truedat101** [comment]
It's on ice.  I would still like to work on it, but at the moment tied up with other projects.  I would like to revisit this project when I circle back on NFC / Blockchain releated projects.

**Comment by cvsae** [comment]
Interested. Watching this.. I will help...

**Comment by truedat101** [comment]
@cvsae excellent.  So where are you at with the other projects out there in the crypto space?  I spent a lot of time reviewing the specs of NEM because they were well documented and there was a lot of source code , java and JS that was easy to grasp and I felt like there was enough here for an implementation starting point .  I realize that a lot of other factors matter since the NEM spec was written, consensus protocols, resistance to various forms of attack, ability to build applications on top, etc... 

I'm also very enthusiastic about ecosystems that can support zero fee networks.  This notion of paying for traffic is bizarre to me.  You can pay for speed, and that makes sense.  But there should be a notion of a zero gas cost transaction.  

Smart contracts are interesting, but there are a lot of details that I believe need to nailed down without losing people in complexity.  Either the contracts are for machines or they are for people.  Both are valid .  But the creators will need to have enough understanding of the long term ramifications of contract design before turning machines loose to negotiate smart contracts.  In some sense, the NASDAQ is a great example of smart contracts that are executed in rapid order every day the market is open.  Buyers and sellers meet, transact, and markets thrive.
